### ISSUE TITLE
what if the target is not the provided database?

### ISSUE THREAD

**Issue by syedzayyan** [dockstring/dockstring#148]
Could it be possible to dock a ligand(s) onto a specific site of a receptor? The ligand(s) are more or less specific but could be promiscuous to other sites on the receptor. Does the target need to be in PDB format if it is possible?

**Comment by AustinT** [comment]
Hi @syedzayyan, thanks for your interest in dockstring! In this package we have pre-specified the site for each receptor by specifying a _bounding box_ for each target in the `conf.txt` files (e.g. https://github.com/dockstring/dockstring/blob/main/dockstring/resources/targets/ACHE_conf.txt). If you would like to add your own target with a custom docking site, you would need to add a `.pdbqt` file and a `conf.txt` file under the `resources/targets` directory of your local installation.

If this answers your question please mark this issue as closed, otherwise we are happy to answer further questions :)
