### ISSUE TITLE
Error with Jupyter

### ISSUE THREAD

**Issue by amarye** [dockstring/dockstring#155]
I have got error, when I ran dockstring using jupyter.

So, I am confusing why did not work using Jupyter.

![Screenshot from 2023-06-06 09-35-41](https://github.com/dockstring/dockstring/assets/55770700/1a9ecb29-bd32-4393-bb79-988ee24d282d)

**Comment by AustinT** [comment]
Hi @amarye, thanks for your interest in dockstring. Dockstring does work with jupyter: probably you did not install it correctly. I suggest adding the lines:

```python
import sys
sys.path.append("/media/nain1/E/home/dockstring
```

I'm closing this issue since it seems like a generic python path issue rather than an issue specific to dockstring, but please re-open the issue if you believe it is a problem with dockstring itself.

**Comment by amarye** [comment]
There is another problem
![Uploading Screenshot from 2023-06-09 10-17-05.png…]()
