### ISSUE TITLE
Is customized target supported? Didn't find related tutorial.

### ISSUE THREAD

**Issue by Bio-bbhe** [dockstring/dockstring#169]

**Comment by Bio-bbhe** [comment]
Hi Austin, thank you for your replying. I noticed that the .txt is a conf file that stores the grid box information. For a predicted model from the AlphaFold Database, which lacks any ligand, we can manually define the grid box information. However, if we have thousands of targets, preparing the grid box information is not easy. May I ask how to batch generate .pdbqt and .txt files? I could try to contribute a tutorial as a PR if I can make this.

**Comment by AustinT** [comment]
Unfortunately we don't know any good way of setting this up automatically. To make dockstring we took `pdbqt` files from the pdb database (i.e. we did not generate them ourselves) and placed the docking boxes manually based on known binding locations, with a bit of adjustment to improve the correlation between docking scores and experimentally measured binding affinities. Not sure how this can be automated.

Of course nothing is stopping you from generating arbitrary protein structures to put into pdbqt files and placing the bounding boxes arbitrarily (or making them large): the docking results just might not be very physically meaningful.

For now I will mark this as an "enhancement" and close the issue since myself and Miguel will not be able to add this feature now. Still happy to respond to further questions though and happy to accept PRs which provide additional targets (provided they are set up in a physically meaningful way)
