### ISSUE TITLE
DockstringError: System 'Windows' not yet supported

### ISSUE THREAD

**Issue by Super-dong94** [dockstring/dockstring#177]
我的计算机上运行出现下面错误，请问如何解决呢？
---------------------------------------------------------------------------
DockstringError                           Traceback (most recent call last)
Cell In[5], line 4
      1 from dockstring import load_target
      3 target = load_target('DRD2')
----> 4 score, aux = target.dock(smiles)

File D:\anaconda3\Lib\site-packages\dockstring\target.py:209, in Target.dock(self, smiles, pH, num_cpus, seed, verbose)
    207 write_mol_to_mol_file(refined_mol, ligand_mol_file)
    208 convert_mol_file_to_pdbqt(ligand_mol_file, ligand_pdbqt)
--> 209 self._dock_pdbqt(ligand_pdbqt, vina_logfile, vina_outfile, seed=seed, num_cpus=num_cpus)
    211 # Process docking output
    212 try:

File D:\anaconda3\Lib\site-packages\dockstring\target.py:140, in Target._dock_pdbqt(self, pdbqt_path, log_path, out_path, seed, num_cpus)
    129 """
    130 Run AutoDock Vina.
    131 
   (...)
    136 :param num_cpus: number of CPU cores available to AutoDock Vina
    137 """
    138 # yapf: disable
    139 cmd_list = [
--> 140     get_vina_path(),
    141     '--receptor', self.pdbqt_path,
    142     '--config', self.conf_path,
    143     '--ligand', pdbqt_path,
    144     '--log', log_path,
    145     '--out', out_path,
    146     '--seed', str(seed),
    147 ]
    148 # yapf: enable
    149 if num_cpus is not None:

File D:\anaconda3\Lib\site-packages\dockstring\utils.py:119, in get_vina_path()
    117 def get_vina_path() -> Path:
    118     """Path pointing to system-dependent AutoDock Vina executable."""
--> 119     path = get_bin_dir() / get_vina_filename()
    120     if not path.is_file():
    121         raise DockstringError('AutoDock Vina executable not found')

File D:\anaconda3\Lib\site-packages\dockstring\utils.py:85, in get_vina_filename()
     83     return 'vina_mac_catalina'
     84 else:
---> 85     raise DockstringError(f"System '{system_name}' not yet supported")

DockstringError: System 'Windows' not yet supported

**Comment by AustinT** [comment]
@Super-dong94 我们maintainers都是外国人，所以我用英文解释。我推荐你用[WSL](https://learn.microsoft.com/en-us/windows/wsl/install)。

The question is: how to resolve this error?

Answer: dockstring includes a binary file for each operating system, so to work on windows a separate file is required. We did not include this file because we want the docking scores outputted by dockstring to be consistent and standardized, but unfortunately every binary file is a bit different. I recommend using Windows Subsystem for Linux (WSL): dockstring works really well on that. This is partly why we haven't emphasized Windows support in the past.

**Comment by RuikangSun** [comment]
目前Dockstring因为依赖项的原因，不支持Windows系统，需要装虚拟机或者用服务器。如果只是想先测试一下的话，诸如[阿里云](https://www.modelscope.cn/my/mynotebook/preset)和[深势科技](https://bohrium.dp.tech/notebooks?activeTab=mine)都提供免费的在线Notebook，对接几百个分子还是很快的。
